name: Conditional Jobs
on: push
jobs:
  run_on_main:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - run: echo "Run on main branch"
  skip_when_test_commit:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'test') }}
    steps:
      - run: echo "ignore when test commit"
