# write foo and read foo
name: Accessing var foo
on: push
jobs:
  foobar:
    runs-on: ubuntu-latest
    steps:
      - id: foo
        run: echo "foo=bar" >> "$GITHUB_OUTPUT"
      - run: echo ${{ steps.foo.outputs.foo }}
