# random step의 결과를 다음 step에서 표시함 "failure" 혹은 "success"
name: print previous step result 
on: push
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - id: random
        run: if [[ $(($RANDOM % 2)) == 0 ]]; then exit 0; else exit 1; fi
      - if: ${{ always() }}
        run: echo ${{ steps.random.outcome }}
